REQUIRED_AUDIT_EVENTS = {
    "AUTH_LOGIN",
    "AUTH_LOGOUT",
    "AUTH_FAILED",

    "RESIDENT_CREATE",
    "RESIDENT_UPDATE",
    "RESIDENT_DELETE",

    "ENROLLMENT_CREATE",
    "ENROLLMENT_EXIT",
    "ENROLLMENT_TRANSFER",

    "INTAKE_SUBMIT",

    "PASS_REQUEST",
    "PASS_APPROVE",
    "PASS_DENY",
    "PASS_CHECKIN",

    "RENT_UPDATE",
    "EMPLOYMENT_UPDATE",

    "CASE_NOTE_CREATE",
    "CASE_NOTE_EDIT",

    "ADMIN_CONFIG_CHANGE",

    "USER_CREATE",
    "USER_ROLE_CHANGE",

    "SYSTEM_BACKUP_RUN",
    "SYSTEM_BACKUP_RESTORE",
}
