from dataclasses import dataclass
from typing import List, Optional


@dataclass
class FieldDefinition:
    key: str
    label: str

    # lifecycle placement
    lifecycle_stage: Optional[str] = None  # demographics, intake, current_status, exit, followup_6m, followup_1y, derived, reporting_only

    # wiring status
    wiring_status: Optional[str] = None  # complete, partial, missing, derived, misaligned

    # where collected
    form_page: Optional[str] = None
    form_field: Optional[str] = None

    # where stored
    table: Optional[str] = None
    column: Optional[str] = None

    # reporting usage
    used_in_stats: bool = False

    # notes
    notes: Optional[str] = None


LOCKED_EDUCATION_NOTE = (
    "Approved values are No High School, Some High School, High School Graduate, GED, "
    "Vocational, Associates, Bachelor, Masters, and Doctorate. This scale should be used "
    "consistently anywhere education level is collected or reported."
)

LOCKED_EXIT_CATEGORY_NOTE = (
    "Approved values are Successful Completion, Positive Exit, Neutral Exit, Negative Exit, "
    "and Administrative Exit. This is a controlled reporting field and should stay locked."
)

LOCKED_EXIT_REASON_NOTE = (
    "Approved values are Program Graduated, Permanent Housing, Family Placement, Health Placement, "
    "Left by Choice, Left Without Notice, Unknown / Lost Contact, Rules Violation, "
    "Non Compliance with Program, Relapse, Behavioral Conflict, Incarceration, "
    "Transferred to Another Program, Medical Discharge, and Safety Removal. "
    "This should be tied to Exit Category in both screen logic and backend validation."
)


FIELDS: List[FieldDefinition] = [
    # ==========================================================
    # BLUEPRINT GROUP 1
    # REPORTING ONLY AND SYSTEM LEVEL FIELDS
    # These are not direct resident collected source fields.
    # Keep these separate from intake, assessment, and exit forms.
    # ==========================================================

    FieldDefinition(
        key="last_updated",
        label="Last updated",
        lifecycle_stage="reporting_only",
        wiring_status="misaligned",
        notes="System managed or PDF only. Not part of resident metrics dataset. Leave outside the intake and exit blueprints.",
    ),
    FieldDefinition(
        key="prog_eval_months",
        label="Prog. Eval. Months",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="program_enrollments",
        column="entry_date",
        used_in_stats=True,
        notes="Derived from entry_date as the two calendar months each year when 6 month program evaluations are due. Keep this in a derived or reporting blueprint, not in a collected form blueprint.",
    ),
    FieldDefinition(
        key="days_sober_today",
        label="Days Sober Today",
        lifecycle_stage="derived",
        wiring_status="derived",
        notes="Calculated from sobriety date or later status, not a direct source field. Best kept in derived reporting logic.",
    ),
    FieldDefinition(
        key="days_at_dwc",
        label="Days at DWC",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="program_enrollments",
        column="exit_date",
        used_in_stats=False,
        notes="Calculated from program_enrollments.entry_date and program_enrollments.exit_date, not manually stored. Derived field only.",
    ),
    FieldDefinition(
        key="grit_difference",
        label="Grit difference",
        lifecycle_stage="derived",
        wiring_status="derived",
        notes="Derived from grit_score_at_entry and grit_at_exit, and displayed on the resident case page when both values exist. Do not collect directly.",
    ),

    # ==========================================================
    # BLUEPRINT GROUP 2
    # DEMOGRAPHICS AND IDENTITY
    # Core identity fields. These belong at intake and should stay
    # separate from progress, exit, and derived outcome fields.
    # ==========================================================

    FieldDefinition(
        key="name_last_first",
        label="Name (Last, First)",
        lifecycle_stage="demographics",
        wiring_status="misaligned",
        form_page="intake_assessment",
        notes="Collected as separate first_name and last_name fields, not as one combined field. Keep combined display as reporting only.",
    ),
    FieldDefinition(
        key="first_name",
        label="First Name",
        lifecycle_stage="demographics",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="first_name",
        table="residents",
        column="first_name",
        used_in_stats=False,
        notes="Collected at intake and stored on the resident record. Core identity blueprint field.",
    ),
    FieldDefinition(
        key="last_name",
        label="Last Name",
        lifecycle_stage="demographics",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="last_name",
        table="residents",
        column="last_name",
        used_in_stats=False,
        notes="Collected at intake and stored on the resident record. Core identity blueprint field.",
    ),
    FieldDefinition(
        key="gender_dataset",
        label="Gender",
        lifecycle_stage="demographics",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="gender",
        table="residents",
        column="gender",
        used_in_stats=True,
        notes="Collected and stored. Allowed values should be limited to M or F. Core demographics blueprint field.",
    ),
    FieldDefinition(
        key="race_dataset",
        label="Race",
        lifecycle_stage="demographics",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="race",
        table="residents",
        column="race",
        used_in_stats=True,
        notes="Collected and stored. Core demographics blueprint field.",
    ),
    FieldDefinition(
        key="woman_age",
        label="Woman Age",
        lifecycle_stage="derived",
        wiring_status="derived",
        form_page="intake_assessment",
        form_field="birth_year",
        table="residents",
        column="birth_year",
        used_in_stats=False,
        notes="Birth year is collected. Age should be calculated later, not stored directly. Keep this in derived reporting logic rather than intake source fields.",
    ),
    FieldDefinition(
        key="phone",
        label="Phone",
        lifecycle_stage="demographics",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="phone",
        table="residents",
        column="phone",
        used_in_stats=False,
        notes="Collected and stored. Identity and contact blueprint field.",
    ),
    FieldDefinition(
        key="email",
        label="Email Address",
        lifecycle_stage="demographics",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="email",
        table="residents",
        column="email",
        used_in_stats=False,
        notes="Collected and stored. Identity and contact blueprint field.",
    ),

    # ==========================================================
    # BLUEPRINT GROUP 3
    # INTAKE BASELINE
    # Fields collected at or immediately tied to intake. These
    # represent the entry snapshot, not later progress.
    # ==========================================================

    FieldDefinition(
        key="date_entered",
        label="Date Entered",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="entry_date",
        table="program_enrollments",
        column="entry_date",
        used_in_stats=True,
        notes="Collected at intake and stored on the enrollment. This is the intake anchor field for many later derived metrics.",
    ),
    FieldDefinition(
        key="sobriety_date",
        label="Sobriety Date",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="sobriety_date",
        table="intake_assessments",
        column="sobriety_date",
        used_in_stats=True,
        notes="Collected and stored as intake baseline.",
    ),
    FieldDefinition(
        key="treatment_grad_date",
        label="Treatment Graduation Date",
        lifecycle_stage="intake",
        wiring_status="missing",
        notes="Historical background field for prior rehab completion date. This means when the resident finished her last rehab treatment before entry. Good candidate for a later intake background subsection.",
    ),
    FieldDefinition(
        key="days_sober_at_entry",
        label="Days Sober At Entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        table="intake_assessments",
        column="days_sober_at_entry",
        used_in_stats=False,
        notes="Derived at intake from sobriety_date and stored in intake_assessments. Intake baseline field, but system calculated.",
    ),
    FieldDefinition(
        key="drug_of_choice",
        label="Drug of Choice",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="drug_of_choice",
        table="intake_assessments",
        column="drug_of_choice",
        used_in_stats=True,
        notes="Collected and stored at intake baseline.",
    ),
    FieldDefinition(
        key="shelter",
        label="Shelter or Program Identifier",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="shelter",
        table="program_enrollments",
        column="shelter",
        used_in_stats=True,
        notes="Current values in use are Abba, Haven House, Haven Too, Gratitude House, Level 9, Exited, and Outreach. This field currently mixes location, program level, and status. Also written to residents.shelter. Do not use for duplicate matching. Future blueprint work should split location, level, and status into cleaner fields.",
    ),
    FieldDefinition(
        key="income_at_entry",
        label="Monthly Income at Entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="income_at_entry",
        table="intake_assessments",
        column="income_at_entry",
        used_in_stats=True,
        notes="Collected and stored. This means monthly income, not annual income. Intake baseline financial field.",
    ),
    FieldDefinition(
        key="last_zipcode_of_residence",
        label="Last Zipcode of residence",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="last_zipcode_residence",
        table="intake_assessments",
        column="last_zipcode_residence",
        used_in_stats=False,
        notes="Collected and stored at intake baseline.",
    ),
    FieldDefinition(
        key="city",
        label="City",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="city",
        table="intake_assessments",
        column="city",
        used_in_stats=False,
        notes="Collected and stored at intake baseline.",
    ),
    FieldDefinition(
        key="veteran",
        label="Veteran",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="veteran",
        table="intake_assessments",
        column="veteran",
        used_in_stats=True,
        notes="Collected and stored at intake baseline.",
    ),
    FieldDefinition(
        key="disability",
        label="Disability Type",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="disability",
        table="intake_assessments",
        column="disability",
        used_in_stats=True,
        notes="Collected and stored. Approved categories are Visual, Deaf, Mental Health, Intellectual, Acquired Brain Injury, Autism Spectrum Disorder, Physical, and Multiple. This is a condition category, not a service need field. Intake baseline field.",
    ),
    FieldDefinition(
        key="education_at_entry",
        label="Education at Entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="education_at_entry",
        table="intake_assessments",
        column="education_at_entry",
        used_in_stats=True,
        notes=LOCKED_EDUCATION_NOTE,
    ),
    FieldDefinition(
        key="length_of_time_in_amarillo",
        label="Length of time in Amarillo upon entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="length_of_time_in_amarillo",
        table="intake_assessments",
        column="length_of_time_in_amarillo",
        used_in_stats=False,
        notes="Collected and stored at intake baseline.",
    ),
    FieldDefinition(
        key="marital_status",
        label="Marital Status",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="marital_status",
        table="intake_assessments",
        column="marital_status",
        used_in_stats=True,
        notes="Collected and stored. Intake baseline field. Verify reporting reads from intake_assessments, not residents.",
    ),
    FieldDefinition(
        key="place_staying_before_entry",
        label="Place staying before entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="prior_living",
        table="intake_assessments",
        column="place_staying_before_entry",
        used_in_stats=False,
        notes="Collected at intake through the prior living field and stored as place_staying_before_entry.",
    ),
    FieldDefinition(
        key="ace_score",
        label="ACE Score at Entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="ace_score",
        table="intake_assessments",
        column="ace_score",
        used_in_stats=True,
        notes="Collected and stored. This is the Adverse Childhood Experiences score and should stay on the 0 to 10 scale.",
    ),
    FieldDefinition(
        key="grit_score_at_entry",
        label="Grit Score at Entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="grit_score",
        table="intake_assessments",
        column="grit_score",
        used_in_stats=False,
        notes="Collected and stored. Intended to reflect persistence or follow through at intake baseline.",
    ),
    FieldDefinition(
        key="sexual_survivor",
        label="Sexual Survivor",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="sexual_survivor",
        table="intake_assessments",
        column="sexual_survivor",
        used_in_stats=True,
        notes="Collected and stored at intake baseline.",
    ),
    FieldDefinition(
        key="dv_survivor",
        label="DV Survivor",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="domestic_violence_history",
        table="intake_assessments",
        column="dv_survivor",
        used_in_stats=True,
        notes="Collected at intake through the domestic violence history field and stored in dv_survivor.",
    ),
    FieldDefinition(
        key="human_trafficking_survivor",
        label="Human Trafficking Survivor",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="human_trafficking_history",
        table="intake_assessments",
        column="human_trafficking_survivor",
        used_in_stats=True,
        notes="Collected at intake through the human trafficking history field and stored in human_trafficking_survivor.",
    ),
    FieldDefinition(
        key="entry_felony_conviction",
        label="Entry Felony Conviction",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="felony_history",
        table="intake_assessments",
        column="entry_felony_conviction",
        used_in_stats=True,
        notes="Collected at intake through the felony history field and stored as entry_felony_conviction.",
    ),
    FieldDefinition(
        key="entry_parole_probation",
        label="Entry Parole or Probation",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="probation_parole",
        table="intake_assessments",
        column="entry_parole_probation",
        used_in_stats=True,
        notes="Collected at intake through the probation or parole field and stored as entry_parole_probation.",
    ),
    FieldDefinition(
        key="drug_court",
        label="Drug Court",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="drug_court",
        table="intake_assessments",
        column="drug_court",
        used_in_stats=True,
        notes="Collected and stored at intake baseline.",
    ),
    FieldDefinition(
        key="warrants_unpaid",
        label="Warrants or Fines Unpaid",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="warrants_unpaid",
        table="intake_assessments",
        column="warrants_unpaid",
        used_in_stats=False,
        notes="Collected and stored at intake baseline.",
    ),
    FieldDefinition(
        key="dental_need_at_entry",
        label="Need Dental on Entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="dental_need",
        table="intake_assessments",
        column="dental_need_at_entry",
        used_in_stats=False,
        notes="Collected at intake through the dental need field and stored as dental_need_at_entry.",
    ),
    FieldDefinition(
        key="vision_need_at_entry",
        label="Need Vision on Entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="vision_need",
        table="intake_assessments",
        column="vision_need_at_entry",
        used_in_stats=False,
        notes="Collected at intake through the vision need field and stored as vision_need_at_entry.",
    ),
    FieldDefinition(
        key="mh_exam_completed",
        label="MH Exam",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="mh_exam_completed",
        table="intake_assessments",
        column="mh_exam_completed",
        used_in_stats=False,
        notes="Collected and stored at intake baseline.",
    ),
    FieldDefinition(
        key="med_exam_completed",
        label="Med Exam",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="med_exam_completed",
        table="intake_assessments",
        column="med_exam_completed",
        used_in_stats=False,
        notes="Collected and stored at intake baseline.",
    ),

    # ==========================================================
    # BLUEPRINT GROUP 4
    # CURRENT STATUS OR DURING PROGRAM
    # These fields change during enrollment and should be handled
    # in a current status or progress blueprint, not pure intake.
    # ==========================================================

    FieldDefinition(
        key="rad_graduation",
        label="RAD Graduation",
        lifecycle_stage="current_status",
        wiring_status="misaligned",
        notes="Program milestone completed during enrollment. RAD is an 8 week milestone inside the larger program and should not be treated as intake or exit only. Future blueprint should place this in a current status or milestone section.",
    ),
    FieldDefinition(
        key="education_program",
        label="Education Program",
        lifecycle_stage="current_status",
        wiring_status="missing",
        notes="Current education track field. Approved values are Secondary, GED, Vocational, and Other. This is separate from education_at_entry and should not be treated as completed education level. Future current status blueprint field.",
    ),
    FieldDefinition(
        key="car_at_entry",
        label="Has Car",
        lifecycle_stage="current_status",
        wiring_status="misaligned",
        form_page="intake_assessment",
        form_field="car_at_entry",
        table="intake_assessments",
        column="car_at_entry",
        used_in_stats=False,
        notes="Business rule says this belongs in assessment as a current condition field, not as an intake baseline field. Current wiring still uses the older at entry naming. Future blueprint should move this to a current status section.",
    ),
    FieldDefinition(
        key="car_insurance_at_entry",
        label="Has Car Insurance",
        lifecycle_stage="current_status",
        wiring_status="misaligned",
        form_page="intake_assessment",
        form_field="car_insurance_at_entry",
        table="intake_assessments",
        column="car_insurance_at_entry",
        used_in_stats=False,
        notes="Business rule says this belongs in assessment as a current condition field, not as an intake baseline field. Current wiring still uses the older at entry naming. Future blueprint should move this to a current status section.",
    ),
    FieldDefinition(
        key="parenting_class_needed",
        label="Parenting Class Needed",
        lifecycle_stage="current_status",
        wiring_status="missing",
        notes="This field means whether parenting class is needed, not whether it was completed. Allowed values should be yes or no. Good fit for a current status or service plan blueprint.",
    ),
    FieldDefinition(
        key="dwc_level_today",
        label="DWC Level Today",
        lifecycle_stage="current_status",
        wiring_status="missing",
        notes="Current program level field. Allowed values are 1, 2, 3, 4, 5, 6, 7, 8, 9, and E. This is a changing current status field, not a fixed intake identity field. Future current status blueprint field.",
    ),

    # ==========================================================
    # BLUEPRINT GROUP 5
    # FAMILY AND CHILD DERIVED METRICS
    # These should trend toward child record driven calculations,
    # not manual entry counts.
    # ==========================================================

    FieldDefinition(
        key="kids_at_dwc",
        label="Kids @ DWC",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="family_snapshots",
        column="kids_at_dwc",
        used_in_stats=True,
        notes="Transitional field. Should be derived from child records rather than treated as manual source of truth. Family blueprint should eventually become child record driven.",
    ),
    FieldDefinition(
        key="kids_served_outside_under_18",
        label="Kids served Outside under 18",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="family_snapshots",
        column="kids_served_outside_under_18",
        used_in_stats=True,
        notes="Transitional field. Should be derived from child records if this metric is still needed.",
    ),
    FieldDefinition(
        key="kids_ages_0_5",
        label="Kids ages 0 to 5",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="family_snapshots",
        column="kids_ages_0_5",
        used_in_stats=True,
        notes="Should be calculated from child records, not manually keyed.",
    ),
    FieldDefinition(
        key="kids_ages_6_11",
        label="Kids ages 6 to 11",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="family_snapshots",
        column="kids_ages_6_11",
        used_in_stats=True,
        notes="Should be calculated from child records, not manually keyed.",
    ),
    FieldDefinition(
        key="kids_ages_12_17",
        label="Kids ages 12 to 17",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="family_snapshots",
        column="kids_ages_12_17",
        used_in_stats=True,
        notes="Should be calculated from child records, not manually keyed.",
    ),
    FieldDefinition(
        key="young_adults_18_21",
        label="Young adults 18 to 21",
        lifecycle_stage="derived",
        wiring_status="missing",
        notes="Household composition reporting field. Not wired. Likely should be derived from dependent records if needed.",
    ),
    FieldDefinition(
        key="adult_children_21_65",
        label="Adult children 21 to 65",
        lifecycle_stage="derived",
        wiring_status="missing",
        notes="Household composition reporting field. Not wired. Likely should be derived from dependent records if needed.",
    ),
    FieldDefinition(
        key="kids_reunited_while_in_program",
        label="Kids reunited while in program",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="family_snapshots",
        column="kids_reunited_while_in_program",
        used_in_stats=True,
        notes="Should eventually be derived from child level records or a child outcome event, not manually keyed.",
    ),
    FieldDefinition(
        key="healthy_babies_born_at_dwc",
        label="Healthy Babies born at DWC",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="family_snapshots",
        column="healthy_babies_born_at_dwc",
        used_in_stats=True,
        notes="Should eventually be derived from child level records, not manually keyed.",
    ),

    # ==========================================================
    # BLUEPRINT GROUP 6
    # EXIT
    # Exit collected fields. These should stay controlled and clean
    # because they directly drive reporting and outcomes.
    # ==========================================================

    FieldDefinition(
        key="date_graduated",
        label="Date Graduated",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="date_graduated",
        table="exit_assessments",
        column="date_graduated",
        used_in_stats=True,
        notes="Collected through exit assessment and stored. Exit blueprint field.",
    ),
    FieldDefinition(
        key="date_exit_dwc",
        label="Date Exit DWC",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="date_exit_dwc",
        table="exit_assessments",
        column="date_exit_dwc",
        used_in_stats=True,
        notes="Collected through exit assessment and stored. Also updates program_enrollments.exit_date.",
    ),
    FieldDefinition(
        key="exit_category",
        label="Exit Category",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="exit_category",
        table="exit_assessments",
        column="exit_category",
        used_in_stats=True,
        notes=LOCKED_EXIT_CATEGORY_NOTE,
    ),
    FieldDefinition(
        key="reason_for_exit",
        label="Exit Reason",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="exit_reason",
        table="exit_assessments",
        column="exit_reason",
        used_in_stats=True,
        notes=LOCKED_EXIT_REASON_NOTE,
    ),
    FieldDefinition(
        key="graduate_dwc",
        label="Graduate DWC",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="graduate_dwc",
        table="exit_assessments",
        column="graduate_dwc",
        used_in_stats=True,
        notes="Collected through exit assessment and stored. Also drives exit outcomes and program reporting.",
    ),
    FieldDefinition(
        key="grit_at_exit",
        label="Grit at Exit",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="grit_at_exit",
        table="exit_assessments",
        column="grit_at_exit",
        used_in_stats=False,
        notes="Collected at exit, validated, and stored.",
    ),
    FieldDefinition(
        key="leave_ama_upon_exit",
        label="Leave Amarillo upon exit",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="leave_ama",
        table="exit_assessments",
        column="leave_ama",
        used_in_stats=True,
        notes="Collected through exit assessment and stored. No means stayed in Amarillo. Yes means left Amarillo and should capture city or Unknown. Keep this in the exit blueprint, not as a generic status field.",
    ),
    FieldDefinition(
        key="received_car_at_exit",
        label="Received Car at Exit",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="received_car",
        table="exit_assessments",
        column="received_car",
        used_in_stats=False,
        notes="Collected through exit assessment and stored.",
    ),
    FieldDefinition(
        key="car_insurance_at_exit",
        label="Car Insurance at Exit",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="car_insurance",
        table="exit_assessments",
        column="car_insurance",
        used_in_stats=False,
        notes="Collected through exit assessment and stored. Business rule should keep this tied to Received Car at Exit.",
    ),
    FieldDefinition(
        key="current_income",
        label="Current Monthly Income",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="income_at_exit",
        table="exit_assessments",
        column="income_at_exit",
        used_in_stats=True,
        notes="Collected through exit assessment and stored as monthly income.",
    ),
    FieldDefinition(
        key="education_at_exit",
        label="Education at Exit",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="education_at_exit",
        table="exit_assessments",
        column="education_at_exit",
        used_in_stats=True,
        notes=LOCKED_EDUCATION_NOTE,
    ),
    FieldDefinition(
        key="dental_needs_met",
        label="Dental Needs Met",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="dental_needs_met",
        table="exit_assessments",
        column="dental_needs_met",
        used_in_stats=False,
        notes="Collected through exit assessment and stored.",
    ),
    FieldDefinition(
        key="vision_needs_met",
        label="Vision Needs Met",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="vision_needs_met",
        table="exit_assessments",
        column="vision_needs_met",
        used_in_stats=False,
        notes="Collected through exit assessment and stored.",
    ),
    FieldDefinition(
        key="obtained_public_insurance",
        label="Obtained Public Insurance",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="obtained_public_insurance",
        table="exit_assessments",
        column="obtained_public_insurance",
        used_in_stats=False,
        notes="Collected through exit assessment and stored as a separate public health insurance field.",
    ),
    FieldDefinition(
        key="private_insurance",
        label="Private Insurance",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="private_insurance",
        table="exit_assessments",
        column="private_insurance",
        used_in_stats=False,
        notes="Collected through exit assessment and stored as a separate private health insurance field.",
    ),

    # ==========================================================
    # BLUEPRINT GROUP 7
    # FOLLOW UP AND LONGER TERM OUTCOMES
    # These should move into a dedicated follow up blueprint when
    # that workflow is built out.
    # ==========================================================

    FieldDefinition(
        key="educational_programs_entered_after_intake",
        label="Educational Programs entered after intake",
        lifecycle_stage="followup_6m",
        wiring_status="missing",
        notes="Progress or outcome field. Not wired. Better suited to followup or progress tracking than intake.",
    ),
    FieldDefinition(
        key="updated_grit",
        label="Updated Grit",
        lifecycle_stage="followup_6m",
        wiring_status="missing",
        notes="Later progress or outcome field. Not wired. Good fit for a follow up blueprint.",
    ),
    FieldDefinition(
        key="did_resident_receive_counseling",
        label="Did Resident Receive Counseling?",
        lifecycle_stage="followup_6m",
        wiring_status="missing",
        notes="Later progress or outcome field. Not wired.",
    ),
    FieldDefinition(
        key="children_receiving_counseling_count",
        label="Children Receiving Counseling Count",
        lifecycle_stage="followup_6m",
        wiring_status="missing",
        notes="Likely belongs in child records or later followup reporting, not intake.",
    ),
    FieldDefinition(
        key="parenting_class_completed",
        label="Parenting Class Completed",
        lifecycle_stage="followup_6m",
        wiring_status="missing",
        notes="Separate completion field. Keep separate from parenting_class_needed. Good fit for follow up or milestone blueprint.",
    ),
    FieldDefinition(
        key="received_car_expense_help",
        label="Received Car Expense Help",
        lifecycle_stage="followup_6m",
        wiring_status="missing",
        notes="Outcome field. Not wired. Could belong in exit or followup depending on business rule.",
    ),
    FieldDefinition(
        key="warrants_or_fines_paid",
        label="Warrants or Fines paid",
        lifecycle_stage="followup_6m",
        wiring_status="missing",
        notes="Later progress or outcome field. Not wired.",
    ),
    FieldDefinition(
        key="income_6_month_graduation",
        label="Income 6 Month Graduation",
        lifecycle_stage="followup_6m",
        wiring_status="partial",
        table="followups",
        column="income_at_followup",
        used_in_stats=False,
        notes="Followup schema can support this with followup_type, but no collection page or insert route found yet. Future follow up blueprint field.",
    ),
    FieldDefinition(
        key="income_1_year_graduation",
        label="Income 1 Year Graduation",
        lifecycle_stage="followup_1y",
        wiring_status="partial",
        table="followups",
        column="income_at_followup",
        used_in_stats=False,
        notes="Followup schema can support this with followup_type, but no collection page or insert route found yet. Future follow up blueprint field.",
    ),
    FieldDefinition(
        key="sober_6_month_graduation",
        label="Sober 6 Month Graduation",
        lifecycle_stage="followup_6m",
        wiring_status="partial",
        table="followups",
        column="sober_at_followup",
        used_in_stats=False,
        notes="Followup schema can support this with followup_type, but no collection page or insert route found yet. Future follow up blueprint field.",
    ),
    FieldDefinition(
        key="sober_1_year_graduation",
        label="Sober 1 Year Graduation",
        lifecycle_stage="followup_1y",
        wiring_status="partial",
        table="followups",
        column="sober_at_followup",
        used_in_stats=False,
        notes="Followup schema can support this with followup_type, but no collection page or insert route found yet. Future follow up blueprint field.",
    ),
    FieldDefinition(
        key="new_mailing_address",
        label="New Mailing Address",
        lifecycle_stage="followup_6m",
        wiring_status="missing",
        notes="Could belong in resident profile maintenance or followup workflow depending on business rule.",
    ),
]


def get_all_fields() -> List[FieldDefinition]:
    return FIELDS
