from dataclasses import dataclass
from typing import List
from typing import Optional


@dataclass
class FieldDefinition:
    key: str
    label: str

    # where collected
    form_page: Optional[str] = None
    form_field: Optional[str] = None

    # where stored
    table: Optional[str] = None
    column: Optional[str] = None

    # reporting usage
    used_in_stats: bool = False

    # notes
    notes: Optional[str] = None


FIELDS: List[FieldDefinition] = [
    FieldDefinition(
        key="last_updated",
        label="Last updated",
        notes="System managed or PDF only. Not part of resident metrics dataset.",
    ),
    FieldDefinition(
        key="prog_eval_months",
        label="Prog. Eval. Months",
        notes="Not wired. No table or route found.",
    ),
    FieldDefinition(
        key="name_last_first",
        label="Name (Last, First)",
        form_page="intake_assessment",
        notes="Collected as separate first_name and last_name fields, not as one combined field.",
    ),
    FieldDefinition(
        key="first_name",
        label="First Name",
        form_page="intake_assessment",
        form_field="first_name",
        table="residents",
        column="first_name",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="last_name",
        label="Last Name",
        form_page="intake_assessment",
        form_field="last_name",
        table="residents",
        column="last_name",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="date_entered",
        label="Date Entered",
        form_page="intake_assessment",
        form_field="date_entered",
        table="program_enrollments",
        column="entry_date",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="sobriety_date",
        label="Sobriety Date",
        form_page="intake_assessment",
        form_field="sobriety_date",
        table="intake_assessments",
        column="sobriety_date",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="treatment_grad_date",
        label="Treatment Grad Date",
        notes="Not wired. No table or route found.",
    ),
    FieldDefinition(
        key="rad_graduation",
        label="RAD graduation",
        notes="Not wired. No table or route found.",
    ),
    FieldDefinition(
        key="days_sober_at_entry",
        label="Days Sober At Entry",
        table="intake_assessments",
        column="days_sober_at_entry",
        used_in_stats=False,
        notes="Schema exists but current intake insert does not populate it.",
    ),
    FieldDefinition(
        key="days_sober_today",
        label="Days Sober Today",
        notes="Not wired. Would require calculation or a later update field.",
    ),
    FieldDefinition(
        key="drug_of_choice",
        label="Drug of Choice",
        form_page="intake_assessment",
        form_field="drug_of_choice",
        table="intake_assessments",
        column="drug_of_choice",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="race_dataset",
        label="Race",
        form_page="intake_assessment",
        form_field="race",
        table="residents",
        column="race",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="gender_dataset",
        label="Gender",
        form_page="intake_assessment",
        form_field="gender",
        table="residents",
        column="gender",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="woman_age",
        label="Woman Age",
        form_page="intake_assessment",
        form_field="birth_year",
        table="residents",
        column="birth_year",
        used_in_stats=False,
        notes="Birth year is collected. Exact age is not stored directly and would be calculated later.",
    ),
    FieldDefinition(
        key="kids_at_dwc",
        label="Kids @ DWC",
        form_page="intake_assessment",
        form_field="children_count",
        table="family_snapshots",
        column="kids_at_dwc",
        used_in_stats=True,
        notes="Derived from intake child fields and stored in family_snapshots.",
    ),
    FieldDefinition(
        key="kids_served_outside_under_18",
        label="Kids served Outside under 18",
        table="family_snapshots",
        column="kids_served_outside_under_18",
        used_in_stats=True,
        notes="Schema exists but current form and insert do not populate it.",
    ),
    FieldDefinition(
        key="kids_ages_0_5",
        label="Kids ages 0-5",
        table="family_snapshots",
        column="kids_ages_0_5",
        used_in_stats=True,
        notes="Schema exists but current form and insert do not populate it.",
    ),
    FieldDefinition(
        key="kids_ages_6_11",
        label="Kids ages 6-11",
        table="family_snapshots",
        column="kids_ages_6_11",
        used_in_stats=True,
        notes="Schema exists but current form and insert do not populate it.",
    ),
    FieldDefinition(
        key="kids_ages_12_17",
        label="Kids ages 12-17",
        table="family_snapshots",
        column="kids_ages_12_17",
        used_in_stats=True,
        notes="Schema exists but current form and insert do not populate it.",
    ),
    FieldDefinition(
        key="young_adults_18_21",
        label="Young adults 18-21",
        notes="Not wired. No table or route found.",
    ),
    FieldDefinition(
        key="adult_children_21_65",
        label="Adult children 21-65",
        notes="Not wired. No table or route found.",
    ),
    FieldDefinition(
        key="kids_reunited_while_in_program",
        label="Kids reunited while in program",
        table="family_snapshots",
        column="kids_reunited_while_in_program",
        used_in_stats=True,
        notes="Schema exists but current form and insert do not populate it.",
    ),
    FieldDefinition(
        key="healthy_babies_born_at_dwc",
        label="Healthy Babies born at DWC",
        form_page="intake_assessment",
        form_field="newborn_at_dwc",
        table="family_snapshots",
        column="healthy_babies_born_at_dwc",
        used_in_stats=True,
        notes="Derived from intake child fields and stored in family_snapshots.",
    ),
    FieldDefinition(
        key="shelter",
        label="SHELTER",
        form_page="intake_assessment",
        form_field="shelter",
        table="program_enrollments",
        column="shelter",
        used_in_stats=True,
        notes="Also written to residents.shelter.",
    ),
    FieldDefinition(
        key="income_at_entry",
        label="Income at Entry",
        form_page="intake_assessment",
        form_field="income_at_entry",
        table="intake_assessments",
        column="income_at_entry",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="last_zipcode_of_residence",
        label="Last Zipcode of residence",
        form_page="intake_assessment",
        form_field="last_zipcode_residence",
        table="intake_assessments",
        column="last_zipcode_residence",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="city",
        label="CIty",
        form_page="intake_assessment",
        form_field="city",
        table="intake_assessments",
        column="city",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="veteran",
        label="Veteran",
        form_page="intake_assessment",
        form_field="veteran",
        table="intake_assessments",
        column="veteran",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="disability",
        label="Dissability",
        form_page="intake_assessment",
        form_field="disability",
        table="intake_assessments",
        column="disability",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="education_at_entry",
        label="Edu at Entry",
        form_page="intake_assessment",
        form_field="education_at_entry",
        table="intake_assessments",
        column="education_at_entry",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="educational_programs_entered_after_intake",
        label="Educational Programs entered after intake",
        notes="Not wired. No field, table, or route found.",
    ),
    FieldDefinition(
        key="car_at_entry",
        label="Car at Entry",
        form_page="intake_assessment",
        form_field="car_at_entry",
        table="intake_assessments",
        column="car_at_entry",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="car_insurance_at_entry",
        label="Car Ins Entry",
        form_page="intake_assessment",
        form_field="car_insurance_at_entry",
        table="intake_assessments",
        column="car_insurance_at_entry",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="length_of_time_in_amarillo",
        label="Length of time in Amarillo upon entry",
        form_page="intake_assessment",
        form_field="length_of_time_in_amarillo",
        table="intake_assessments",
        column="length_of_time_in_amarillo",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="marital_status",
        label="Marital Status:",
        form_page="intake_assessment",
        form_field="marital_status",
        table="intake_assessments",
        column="marital_status",
        used_in_stats=True,
        notes="Collected and stored. Verify reporting query is reading from intake_assessments, not residents.",
    ),
    FieldDefinition(
        key="place_staying_before_entry",
        label="Place staying before entry:",
        form_page="intake_assessment",
        form_field="place_staying_before_entry",
        table="intake_assessments",
        column="place_staying_before_entry",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="ace_score",
        label="ACE score at entry",
        form_page="intake_assessment",
        form_field="ace_score",
        table="intake_assessments",
        column="ace_score",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="grit_score_at_entry",
        label="Grit Scrore at entry",
        form_page="intake_assessment",
        form_field="grit_score",
        table="intake_assessments",
        column="grit_score",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="updated_grit",
        label="Updated Grit",
        notes="Not wired. No follow up or update field found.",
    ),
    FieldDefinition(
        key="sexual_survivor",
        label="Sexual Survivor",
        form_page="intake_assessment",
        form_field="sexual_survivor",
        table="intake_assessments",
        column="sexual_survivor",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="dv_survivor",
        label="DV Survivor",
        form_page="intake_assessment",
        form_field="dv_survivor",
        table="intake_assessments",
        column="dv_survivor",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="human_trafficking_survivor",
        label="Human Trafficking Survivor",
        form_page="intake_assessment",
        form_field="human_trafficking_survivor",
        table="intake_assessments",
        column="human_trafficking_survivor",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="entry_felony_conviction",
        label="Entry Felony Conviction",
        form_page="intake_assessment",
        form_field="entry_felony_conviction",
        table="intake_assessments",
        column="entry_felony_conviction",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="entry_parole_probation",
        label="Entry Parole/Probation",
        form_page="intake_assessment",
        form_field="entry_parole_probation",
        table="intake_assessments",
        column="entry_parole_probation",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="drug_court",
        label="Drug Court Y/N",
        form_page="intake_assessment",
        form_field="drug_court",
        table="intake_assessments",
        column="drug_court",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="warrants_unpaid",
        label="Warrants or Fines Unpaid",
        form_page="intake_assessment",
        form_field="warrants_unpaid",
        table="intake_assessments",
        column="warrants_unpaid",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="dental_need_at_entry",
        label="Need Dental on Entry",
        form_page="intake_assessment",
        form_field="dental_need_at_entry",
        table="intake_assessments",
        column="dental_need_at_entry",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="vision_need_at_entry",
        label="Need Vision on Entry",
        form_page="intake_assessment",
        form_field="vision_need_at_entry",
        table="intake_assessments",
        column="vision_need_at_entry",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="mh_exam_completed",
        label="MH Exam",
        form_page="intake_assessment",
        form_field="mh_exam_completed",
        table="intake_assessments",
        column="mh_exam_completed",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="med_exam_completed",
        label="Med Exam",
        form_page="intake_assessment",
        form_field="med_exam_completed",
        table="intake_assessments",
        column="med_exam_completed",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="did_resident_receive_counseling",
        label="Did Resident Receive Counseling?",
        notes="Not wired. No field, table, or route found.",
    ),
    FieldDefinition(
        key="children_receiving_counseling_count",
        label="# of children Receiving Counseling",
        notes="Not wired. No field, table, or route found.",
    ),
    FieldDefinition(
        key="parenting_class_completed",
        label="Parenting Class Completed",
        notes="Not wired. No field, table, or route found.",
    ),
    FieldDefinition(
        key="dwc_level_today_or_exit",
        label="DWC Level Today or Exit",
        notes="Weekly submissions keep this as PDF or weekly snapshot material only. Not wired into the master resident metrics dataset.",
    ),
    FieldDefinition(
        key="date_graduated",
        label="Date Graduated",
        table="exit_assessments",
        column="date_graduated",
        used_in_stats=True,
        notes="Exit schema exists but no collection page or insert route found.",
    ),
    FieldDefinition(
        key="date_exit_dwc",
        label="Date Exit DWC",
        table="exit_assessments",
        column="date_exit_dwc",
        used_in_stats=True,
        notes="Exit schema exists but no collection page or insert route found.",
    ),
    FieldDefinition(
        key="days_at_dwc",
        label="Days at DWC",
        notes="Not stored. Could be calculated later from entry date and exit date.",
    ),
    FieldDefinition(
        key="reason_for_exit",
        label="Reason for exit",
        table="exit_assessments",
        column="exit_reason",
        used_in_stats=True,
        notes="Exit schema exists but no collection page or insert route found.",
    ),
    FieldDefinition(
        key="graduate_dwc",
        label="Graduate DWC",
        table="exit_assessments",
        column="graduate_dwc",
        used_in_stats=True,
        notes="Exit schema exists but no collection page or insert route found.",
    ),
    FieldDefinition(
        key="grit_at_exit",
        label="Grit at Exit",
        notes="Not wired. No exit grit field found.",
    ),
    FieldDefinition(
        key="grit_difference",
        label="Grit difference",
        notes="Not wired. Would depend on grit at exit.",
    ),
    FieldDefinition(
        key="leave_ama_upon_exit",
        label="Leave AMA upon exit",
        table="exit_assessments",
        column="leave_ama",
        used_in_stats=True,
        notes="Exit schema exists but no collection page or insert route found.",
    ),
    FieldDefinition(
        key="received_car_at_exit",
        label="Received Car/car at exit",
        table="exit_assessments",
        column="received_car",
        used_in_stats=False,
        notes="Exit schema exists but no collection page or insert route found.",
    ),
    FieldDefinition(
        key="car_insurance_at_exit",
        label="Car ins.",
        table="exit_assessments",
        column="car_insurance",
        used_in_stats=False,
        notes="Exit schema exists but no collection page or insert route found.",
    ),
    FieldDefinition(
        key="received_car_expense_help",
        label="Recieved car expense help",
        notes="Not wired. No field, table, or route found.",
    ),
    FieldDefinition(
        key="current_income",
        label="Current income",
        table="exit_assessments",
        column="income_at_exit",
        used_in_stats=True,
        notes="Exit schema exists but no collection page or insert route found.",
    ),
    FieldDefinition(
        key="education_at_exit",
        label="Edu at Exit/current education level",
        table="exit_assessments",
        column="education_at_exit",
        used_in_stats=True,
        notes="Exit schema exists but no collection page or insert route found.",
    ),
    FieldDefinition(
        key="warrants_or_fines_paid",
        label="Warrants or Fines paid",
        notes="Not wired. No field, table, or route found.",
    ),
    FieldDefinition(
        key="dental_needs_met",
        label="Dental Needs Met",
        table="exit_assessments",
        column="dental_needs_met",
        used_in_stats=False,
        notes="Exit schema exists but no collection page or insert route found.",
    ),
    FieldDefinition(
        key="vision_needs_met",
        label="Vision Needs Met",
        table="exit_assessments",
        column="vision_needs_met",
        used_in_stats=False,
        notes="Exit schema exists but no collection page or insert route found.",
    ),
    FieldDefinition(
        key="obtained_public_insurance",
        label="Obtained Public Insurance",
        table="exit_assessments",
        column="obtained_insurance",
        used_in_stats=False,
        notes="Only one combined insurance field exists in schema. No separate public insurance field and no collection route found.",
    ),
    FieldDefinition(
        key="private_insurance",
        label="private insurance",
        table="exit_assessments",
        column="obtained_insurance",
        used_in_stats=False,
        notes="No separate private insurance column found. Current schema only has one combined insurance field.",
    ),
    FieldDefinition(
        key="phone",
        label="Phone #",
        form_page="intake_assessment",
        form_field="phone",
        table="residents",
        column="phone",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="income_6_month_graduation",
        label="Income 6 mo. Graduation",
        table="followups",
        column="income_at_followup",
        used_in_stats=False,
        notes="Followup schema can support this with followup_type, but no collection page or insert route found.",
    ),
    FieldDefinition(
        key="income_1_year_graduation",
        label="Income 1 yr Graduation",
        table="followups",
        column="income_at_followup",
        used_in_stats=False,
        notes="Followup schema can support this with followup_type, but no collection page or insert route found.",
    ),
    FieldDefinition(
        key="sober_6_month_graduation",
        label="Sober 6 mo. Graduation",
        table="followups",
        column="sober_at_followup",
        used_in_stats=False,
        notes="Followup schema can support this with followup_type, but no collection page or insert route found.",
    ),
    FieldDefinition(
        key="sober_1_year_graduation",
        label="Sober 1 yr Graduation",
        table="followups",
        column="sober_at_followup",
        used_in_stats=False,
        notes="Followup schema can support this with followup_type, but no collection page or insert route found.",
    ),
    FieldDefinition(
        key="email",
        label="Email address",
        form_page="intake_assessment",
        form_field="email",
        table="residents",
        column="email",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="new_mailing_address",
        label="New mailing address",
        notes="Not wired. No field, table, or route found.",
    ),
]


def get_all_fields() -> List[FieldDefinition]:
    return FIELDS
