from dataclasses import dataclass
from typing import List, Optional


@dataclass
class FieldDefinition:
    key: str
    label: str

    # lifecycle placement
    lifecycle_stage: Optional[str] = None  # demographics, intake, exit, followup_6m, followup_1y, derived, reporting_only

    # wiring status
    wiring_status: Optional[str] = None  # complete, partial, missing, derived, misaligned

    # where collected
    form_page: Optional[str] = None
    form_field: Optional[str] = None

    # where stored
    table: Optional[str] = None
    column: Optional[str] = None

    # reporting usage
    used_in_stats: bool = False

    # notes
    notes: Optional[str] = None


FIELDS: List[FieldDefinition] = [
    FieldDefinition(
        key="last_updated",
        label="Last updated",
        lifecycle_stage="reporting_only",
        wiring_status="misaligned",
        notes="System managed or PDF only. Not part of resident metrics dataset.",
    ),
    FieldDefinition(
        key="prog_eval_months",
        label="Prog. Eval. Months",
        lifecycle_stage="reporting_only",
        wiring_status="missing",
        notes="Reporting metric only. Not wired. No table or route found.",
    ),
    FieldDefinition(
        key="name_last_first",
        label="Name (Last, First)",
        lifecycle_stage="demographics",
        wiring_status="misaligned",
        form_page="intake_assessment",
        notes="Collected as separate first_name and last_name fields, not as one combined field.",
    ),
    FieldDefinition(
        key="first_name",
        label="First Name",
        lifecycle_stage="demographics",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="first_name",
        table="residents",
        column="first_name",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="last_name",
        label="Last Name",
        lifecycle_stage="demographics",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="last_name",
        table="residents",
        column="last_name",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="date_entered",
        label="Date Entered",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="date_entered",
        table="program_enrollments",
        column="entry_date",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="sobriety_date",
        label="Sobriety Date",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="sobriety_date",
        table="intake_assessments",
        column="sobriety_date",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="treatment_grad_date",
        label="Treatment Grad Date",
        lifecycle_stage="exit",
        wiring_status="missing",
        notes="Outcome field. Not wired. No table or route found.",
    ),
    FieldDefinition(
        key="rad_graduation",
        label="RAD graduation",
        lifecycle_stage="exit",
        wiring_status="missing",
        notes="Outcome field. Not wired. No table or route found.",
    ),
    FieldDefinition(
        key="days_sober_at_entry",
        label="Days Sober At Entry",
        lifecycle_stage="intake",
        wiring_status="partial",
        table="intake_assessments",
        column="days_sober_at_entry",
        used_in_stats=False,
        notes="Schema exists but current intake insert does not populate it.",
    ),
    FieldDefinition(
        key="days_sober_today",
        label="Days Sober Today",
        lifecycle_stage="derived",
        wiring_status="derived",
        notes="Calculated from sobriety date or later status, not a direct source field.",
    ),
    FieldDefinition(
        key="drug_of_choice",
        label="Drug of Choice",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="drug_of_choice",
        table="intake_assessments",
        column="drug_of_choice",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="race_dataset",
        label="Race",
        lifecycle_stage="demographics",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="race",
        table="residents",
        column="race",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="gender_dataset",
        label="Gender",
        lifecycle_stage="demographics",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="gender",
        table="residents",
        column="gender",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="woman_age",
        label="Woman Age",
        lifecycle_stage="derived",
        wiring_status="derived",
        form_page="intake_assessment",
        form_field="birth_year",
        table="residents",
        column="birth_year",
        used_in_stats=False,
        notes="Birth year is collected. Age should be calculated later, not stored directly.",
    ),
    FieldDefinition(
        key="kids_at_dwc",
        label="Kids @ DWC",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="family_snapshots",
        column="kids_at_dwc",
        used_in_stats=True,
        notes="Transitional field. Should be derived from child records rather than treated as manual source of truth.",
    ),
    FieldDefinition(
        key="kids_served_outside_under_18",
        label="Kids served Outside under 18",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="family_snapshots",
        column="kids_served_outside_under_18",
        used_in_stats=True,
        notes="Transitional field. Should be derived from child records if this metric is still needed.",
    ),
    FieldDefinition(
        key="kids_ages_0_5",
        label="Kids ages 0-5",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="family_snapshots",
        column="kids_ages_0_5",
        used_in_stats=True,
        notes="Should be calculated from child records, not manually keyed.",
    ),
    FieldDefinition(
        key="kids_ages_6_11",
        label="Kids ages 6-11",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="family_snapshots",
        column="kids_ages_6_11",
        used_in_stats=True,
        notes="Should be calculated from child records, not manually keyed.",
    ),
    FieldDefinition(
        key="kids_ages_12_17",
        label="Kids ages 12-17",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="family_snapshots",
        column="kids_ages_12_17",
        used_in_stats=True,
        notes="Should be calculated from child records, not manually keyed.",
    ),
    FieldDefinition(
        key="young_adults_18_21",
        label="Young adults 18-21",
        lifecycle_stage="derived",
        wiring_status="missing",
        notes="Household composition reporting field. Not wired. Likely should be derived from dependent records if needed.",
    ),
    FieldDefinition(
        key="adult_children_21_65",
        label="Adult children 21-65",
        lifecycle_stage="derived",
        wiring_status="missing",
        notes="Household composition reporting field. Not wired. Likely should be derived from dependent records if needed.",
    ),
    FieldDefinition(
        key="kids_reunited_while_in_program",
        label="Kids reunited while in program",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="family_snapshots",
        column="kids_reunited_while_in_program",
        used_in_stats=True,
        notes="Should eventually be derived from child level records or a child outcome event, not manually keyed.",
    ),
    FieldDefinition(
        key="healthy_babies_born_at_dwc",
        label="Healthy Babies born at DWC",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="family_snapshots",
        column="healthy_babies_born_at_dwc",
        used_in_stats=True,
        notes="Should eventually be derived from child level records, not manually keyed.",
    ),
    FieldDefinition(
        key="shelter",
        label="SHELTER",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="shelter",
        table="program_enrollments",
        column="shelter",
        used_in_stats=True,
        notes="Also written to residents.shelter.",
    ),
    FieldDefinition(
        key="income_at_entry",
        label="Income at Entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="income_at_entry",
        table="intake_assessments",
        column="income_at_entry",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="last_zipcode_of_residence",
        label="Last Zipcode of residence",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="last_zipcode_residence",
        table="intake_assessments",
        column="last_zipcode_residence",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="city",
        label="City",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="city",
        table="intake_assessments",
        column="city",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="veteran",
        label="Veteran",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="veteran",
        table="intake_assessments",
        column="veteran",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="disability",
        label="Disability",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="disability",
        table="intake_assessments",
        column="disability",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="education_at_entry",
        label="Edu at Entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="education_at_entry",
        table="intake_assessments",
        column="education_at_entry",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="educational_programs_entered_after_intake",
        label="Educational Programs entered after intake",
        lifecycle_stage="followup_6m",
        wiring_status="missing",
        notes="Progress or outcome field. Not wired. Better suited to followup or progress tracking than intake.",
    ),
    FieldDefinition(
        key="car_at_entry",
        label="Car at Entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="car_at_entry",
        table="intake_assessments",
        column="car_at_entry",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="car_insurance_at_entry",
        label="Car Ins Entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="car_insurance_at_entry",
        table="intake_assessments",
        column="car_insurance_at_entry",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="length_of_time_in_amarillo",
        label="Length of time in Amarillo upon entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="length_of_time_in_amarillo",
        table="intake_assessments",
        column="length_of_time_in_amarillo",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="marital_status",
        label="Marital Status",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="marital_status",
        table="intake_assessments",
        column="marital_status",
        used_in_stats=True,
        notes="Collected and stored. Verify reporting reads from intake_assessments, not residents.",
    ),
    FieldDefinition(
        key="place_staying_before_entry",
        label="Place staying before entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="place_staying_before_entry",
        table="intake_assessments",
        column="place_staying_before_entry",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="ace_score",
        label="ACE score at entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="ace_score",
        table="intake_assessments",
        column="ace_score",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="grit_score_at_entry",
        label="Grit score at entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="grit_score",
        table="intake_assessments",
        column="grit_score",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="updated_grit",
        label="Updated Grit",
        lifecycle_stage="followup_6m",
        wiring_status="missing",
        notes="Later progress or outcome field. Not wired.",
    ),
    FieldDefinition(
        key="sexual_survivor",
        label="Sexual Survivor",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="sexual_survivor",
        table="intake_assessments",
        column="sexual_survivor",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="dv_survivor",
        label="DV Survivor",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="dv_survivor",
        table="intake_assessments",
        column="dv_survivor",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="human_trafficking_survivor",
        label="Human Trafficking Survivor",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="human_trafficking_survivor",
        table="intake_assessments",
        column="human_trafficking_survivor",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="entry_felony_conviction",
        label="Entry Felony Conviction",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="entry_felony_conviction",
        table="intake_assessments",
        column="entry_felony_conviction",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="entry_parole_probation",
        label="Entry Parole/Probation",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="entry_parole_probation",
        table="intake_assessments",
        column="entry_parole_probation",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="drug_court",
        label="Drug Court",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="drug_court",
        table="intake_assessments",
        column="drug_court",
        used_in_stats=True,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="warrants_unpaid",
        label="Warrants or Fines Unpaid",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="warrants_unpaid",
        table="intake_assessments",
        column="warrants_unpaid",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="dental_need_at_entry",
        label="Need Dental on Entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="dental_need_at_entry",
        table="intake_assessments",
        column="dental_need_at_entry",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="vision_need_at_entry",
        label="Need Vision on Entry",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="vision_need_at_entry",
        table="intake_assessments",
        column="vision_need_at_entry",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="mh_exam_completed",
        label="MH Exam",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="mh_exam_completed",
        table="intake_assessments",
        column="mh_exam_completed",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="med_exam_completed",
        label="Med Exam",
        lifecycle_stage="intake",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="med_exam_completed",
        table="intake_assessments",
        column="med_exam_completed",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="did_resident_receive_counseling",
        label="Did Resident Receive Counseling?",
        lifecycle_stage="followup_6m",
        wiring_status="missing",
        notes="Later progress or outcome field. Not wired.",
    ),
    FieldDefinition(
        key="children_receiving_counseling_count",
        label="# of children Receiving Counseling",
        lifecycle_stage="followup_6m",
        wiring_status="missing",
        notes="Likely belongs in child records or later followup reporting, not intake.",
    ),
    FieldDefinition(
        key="parenting_class_completed",
        label="Parenting Class Completed",
        lifecycle_stage="followup_6m",
        wiring_status="missing",
        notes="Later progress or outcome field. Not wired.",
    ),
    FieldDefinition(
        key="dwc_level_today_or_exit",
        label="DWC Level Today or Exit",
        lifecycle_stage="reporting_only",
        wiring_status="misaligned",
        notes="Weekly submissions keep this as PDF or weekly snapshot material only. Not wired into the master resident metrics dataset.",
    ),
    FieldDefinition(
        key="date_graduated",
        label="Date Graduated",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="date_graduated",
        table="exit_assessments",
        column="date_graduated",
        used_in_stats=True,
        notes="Collected through exit assessment and stored.",
    ),
    FieldDefinition(
        key="date_exit_dwc",
        label="Date Exit DWC",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="date_exit_dwc",
        table="exit_assessments",
        column="date_exit_dwc",
        used_in_stats=True,
        notes="Collected through exit assessment and stored. Also updates program_enrollments.exit_date.",
    ),
    FieldDefinition(
        key="days_at_dwc",
        label="Days at DWC",
        lifecycle_stage="derived",
        wiring_status="derived",
        table="program_enrollments",
        column="exit_date",
        used_in_stats=False,
        notes="Calculated from program_enrollments.entry_date and program_enrollments.exit_date, not manually stored.",
    ),
    FieldDefinition(
        key="reason_for_exit",
        label="Reason for exit",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="exit_reason",
        table="exit_assessments",
        column="exit_reason",
        used_in_stats=True,
        notes="Collected through exit assessment and stored.",
    ),
    FieldDefinition(
        key="graduate_dwc",
        label="Graduate DWC",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="graduate_dwc",
        table="exit_assessments",
        column="graduate_dwc",
        used_in_stats=True,
        notes="Collected through exit assessment and stored. Also drives enrollment program status when submitted.",
    ),
    FieldDefinition(
        key="grit_at_exit",
        label="Grit at Exit",
        lifecycle_stage="exit",
        wiring_status="missing",
        notes="Exit field not wired yet.",
    ),
    FieldDefinition(
        key="grit_difference",
        label="Grit difference",
        lifecycle_stage="derived",
        wiring_status="derived",
        notes="Derived from grit_score_at_entry and grit_at_exit once exit grit exists.",
    ),
    FieldDefinition(
        key="leave_ama_upon_exit",
        label="Leave AMA upon exit",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="leave_ama",
        table="exit_assessments",
        column="leave_ama",
        used_in_stats=True,
        notes="Collected through exit assessment and stored. Also drives enrollment program status when submitted.",
    ),
    FieldDefinition(
        key="received_car_at_exit",
        label="Received Car/car at exit",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="received_car",
        table="exit_assessments",
        column="received_car",
        used_in_stats=False,
        notes="Collected through exit assessment and stored.",
    ),
    FieldDefinition(
        key="car_insurance_at_exit",
        label="Car ins.",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="car_insurance",
        table="exit_assessments",
        column="car_insurance",
        used_in_stats=False,
        notes="Collected through exit assessment and stored.",
    ),
    FieldDefinition(
        key="received_car_expense_help",
        label="Recieved car expense help",
        lifecycle_stage="followup_6m",
        wiring_status="missing",
        notes="Outcome field. Not wired. Could belong in exit or followup depending on business rule.",
    ),
    FieldDefinition(
        key="current_income",
        label="Current income",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="income_at_exit",
        table="exit_assessments",
        column="income_at_exit",
        used_in_stats=True,
        notes="Collected through exit assessment and stored.",
    ),
    FieldDefinition(
        key="education_at_exit",
        label="Edu at Exit/current education level",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="education_at_exit",
        table="exit_assessments",
        column="education_at_exit",
        used_in_stats=True,
        notes="Collected through exit assessment and stored.",
    ),
    FieldDefinition(
        key="warrants_or_fines_paid",
        label="Warrants or Fines paid",
        lifecycle_stage="followup_6m",
        wiring_status="missing",
        notes="Later progress or outcome field. Not wired.",
    ),
    FieldDefinition(
        key="dental_needs_met",
        label="Dental Needs Met",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="dental_needs_met",
        table="exit_assessments",
        column="dental_needs_met",
        used_in_stats=False,
        notes="Collected through exit assessment and stored.",
    ),
    FieldDefinition(
        key="vision_needs_met",
        label="Vision Needs Met",
        lifecycle_stage="exit",
        wiring_status="complete",
        form_page="exit_assessment",
        form_field="vision_needs_met",
        table="exit_assessments",
        column="vision_needs_met",
        used_in_stats=False,
        notes="Collected through exit assessment and stored.",
    ),
    FieldDefinition(
        key="obtained_public_insurance",
        label="Obtained Public Insurance",
        lifecycle_stage="exit",
        wiring_status="misaligned",
        form_page="exit_assessment",
        form_field="obtained_insurance",
        table="exit_assessments",
        column="obtained_insurance",
        used_in_stats=False,
        notes="Current schema only has one combined insurance field. This spreadsheet field is mapped to that combined field for now.",
    ),
    FieldDefinition(
        key="private_insurance",
        label="private insurance",
        lifecycle_stage="exit",
        wiring_status="misaligned",
        form_page="exit_assessment",
        form_field="obtained_insurance",
        table="exit_assessments",
        column="obtained_insurance",
        used_in_stats=False,
        notes="Current schema only has one combined insurance field. This spreadsheet field is mapped to that combined field for now.",
    ),
    FieldDefinition(
        key="phone",
        label="Phone #",
        lifecycle_stage="demographics",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="phone",
        table="residents",
        column="phone",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="income_6_month_graduation",
        label="Income 6 mo. Graduation",
        lifecycle_stage="followup_6m",
        wiring_status="partial",
        table="followups",
        column="income_at_followup",
        used_in_stats=False,
        notes="Followup schema can support this with followup_type, but no collection page or insert route found yet.",
    ),
    FieldDefinition(
        key="income_1_year_graduation",
        label="Income 1 yr Graduation",
        lifecycle_stage="followup_1y",
        wiring_status="partial",
        table="followups",
        column="income_at_followup",
        used_in_stats=False,
        notes="Followup schema can support this with followup_type, but no collection page or insert route found yet.",
    ),
    FieldDefinition(
        key="sober_6_month_graduation",
        label="Sober 6 mo. Graduation",
        lifecycle_stage="followup_6m",
        wiring_status="partial",
        table="followups",
        column="sober_at_followup",
        used_in_stats=False,
        notes="Followup schema can support this with followup_type, but no collection page or insert route found yet.",
    ),
    FieldDefinition(
        key="sober_1_year_graduation",
        label="Sober 1 yr Graduation",
        lifecycle_stage="followup_1y",
        wiring_status="partial",
        table="followups",
        column="sober_at_followup",
        used_in_stats=False,
        notes="Followup schema can support this with followup_type, but no collection page or insert route found yet.",
    ),
    FieldDefinition(
        key="email",
        label="Email address",
        lifecycle_stage="demographics",
        wiring_status="complete",
        form_page="intake_assessment",
        form_field="email",
        table="residents",
        column="email",
        used_in_stats=False,
        notes="Collected and stored.",
    ),
    FieldDefinition(
        key="new_mailing_address",
        label="New mailing address",
        lifecycle_stage="followup_6m",
        wiring_status="missing",
        notes="Could belong in resident profile maintenance or followup workflow depending on business rule.",
    ),
]


def get_all_fields() -> List[FieldDefinition]:
    return FIELDS
