KIOSK_ACTIVITY_CATEGORY_SEEDS = {
    "haven": [
        ("Work", True, True, None, False),
        ("Volunteer", False, True, None, False),
        ("AA or NA Meeting", False, True, None, False),
        ("Medical or Health", False, True, None, False),
        ("Legal", False, True, None, False),
        ("Program", False, True, None, False),
        ("Job Search", False, True, None, False),
        ("Social Services", False, True, None, False),
        ("Education", False, True, None, False),
        ("Church", False, True, None, False),
        ("Store", False, False, None, False),
        ("Pass", False, False, None, True),
        ("Other Approved Activity", False, False, None, False),
    ],
    "gratitude": [
        ("Work", True, True, None, False),
        ("Volunteer", False, True, None, False),
        ("AA or NA Meeting", False, True, None, False),
        ("Medical or Health", False, True, None, False),
        ("Legal", False, True, None, False),
        ("Program", False, True, None, False),
        ("Job Search", False, True, None, False),
        ("Social Services", False, True, None, False),
        ("Education", False, True, None, False),
        ("Church", False, True, None, False),
        ("Daycare or School Drop Off", False, False, None, False),
        ("Store", False, False, None, False),
        ("Pass", False, False, None, True),
        ("Other Approved Activity", False, False, None, False),
    ],
    "abba": [
        ("Work", True, True, None, False),
        ("Volunteer", False, True, None, False),
        ("AA or NA Meeting", False, True, None, False),
        ("Medical or Health", False, True, None, False),
        ("Legal", False, True, None, False),
        ("Program", False, True, None, False),
        ("Job Search", False, True, None, False),
        ("Social Services", False, True, None, False),
        ("Education", False, True, None, False),
        ("Church", False, True, None, False),
        ("Daycare or School Drop Off", False, False, None, False),
        ("Store", False, False, None, False),
        ("Pass", False, False, None, True),
        ("Free Time", False, False, None, False),
        ("Other Approved Activity", False, False, None, False),
    ],
}
