KIOSK_CATEGORY_SEEDS = {
    "haven house": [
        ("Employment", True, True, None, False),
        ("RAD", True, True, None, False),
        ("Job Search", False, True, None, False),
        ("AA or NA Meeting", False, True, None, False),
        ("Church", False, True, None, False),
        ("Doctor Appointment", False, True, None, False),
        ("Counseling", False, True, None, False),
        ("Step Work", False, True, 2.0, False),
        ("Sponsor Meeting", False, True, 1.0, False),
        ("Volunteer or Community Service", False, True, None, False),
        ("School", False, True, None, False),
        ("Legal Obligation", False, True, None, False),
        ("Store", False, False, None, False),
        ("Pass", False, False, None, True),
        ("Other Approved Activity", False, False, None, False),
    ],
    "gratitude house": [
        ("Employment", True, True, None, False),
        ("Job Search", False, True, None, False),
        ("AA or NA Meeting", False, True, None, False),
        ("Church", False, True, None, False),
        ("Doctor Appointment", False, True, None, False),
        ("Counseling", False, True, None, False),
        ("Step Work", False, True, 2.0, False),
        ("Sponsor Meeting", False, True, 1.0, False),
        ("Volunteer or Community Service", False, True, None, False),
        ("School", False, True, None, False),
        ("Daycare or School Drop Off", False, False, None, False),
        ("Legal Obligation", False, True, None, False),
        ("Store", False, False, None, False),
        ("Pass", False, False, None, True),
        ("Other Approved Activity", False, False, None, False),
    ],
    "abba house": [
        ("Employment", True, True, None, False),
        ("Job Search", False, True, None, False),
        ("AA or NA Meeting", False, True, None, False),
        ("Church", False, True, None, False),
        ("Doctor Appointment", False, True, None, False),
        ("Counseling", False, True, None, False),
        ("Step Work", False, True, 2.0, False),
        ("Sponsor Meeting", False, True, 1.0, False),
        ("Volunteer or Community Service", False, True, None, False),
        ("School", False, True, None, False),
        ("Daycare or School Drop Off", False, False, None, False),
        ("Legal Obligation", False, True, None, False),
        ("Store", False, False, None, False),
        ("Pass", False, False, None, True),
        ("Free Time", False, False, None, False),
        ("Other Approved Activity", False, False, None, False),
    ],
}
