name: Dependency Review

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    continue-on-error: true
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          deny-licenses: GPL-2.0, GPL-3.0, AGPL-1.0, AGPL-3.0
